### ISSUE TITLE
Add Tableau Support

### ISSUE THREAD

**Issue by dai-chen** [opendistro-for-elasticsearch/sql#15]
Make SQL accessible by Tableau via JDBC driver.

**Comment by drusellers** [comment]
I would love to see this feature work. I recently tried to connect Tableau to the OpenDistro version of Elasticsearch and I kept getting issues where tableau didn't think that it could connect to ES. My guess is that this is due to Tableau sending commands that didn't make sense to ES. I've included some screenshots of the requests and responses here for completeness.

![image](https://user-images.githubusercontent.com/63355/65459728-1a18f200-de16-11e9-8b3b-72def3996a3d.png)

response

![image](https://user-images.githubusercontent.com/63355/65459801-3f0d6500-de16-11e9-874f-e95ad8871890.png)


or

![image](https://user-images.githubusercontent.com/63355/65459875-68c68c00-de16-11e9-81a6-17273629247e.png)

response

![image](https://user-images.githubusercontent.com/63355/65459942-83990080-de16-11e9-8a9b-a1c2a2f0e3ac.png)


Happy to answer any questions anyone might have.

**Comment by dai-chen** [comment]
> I would love to see this feature work. I recently tried to connect Tableau to the OpenDistro version of Elasticsearch and I kept getting issues where tableau didn't think that it could connect to ES. My guess is that this is due to Tableau sending commands that didn't make sense to ES. I've included some screenshots of the requests and responses here for completeness.
> 
> ![image](https://user-images.githubusercontent.com/63355/65459728-1a18f200-de16-11e9-8b3b-72def3996a3d.png)
> 
> response
> 
> ![image](https://user-images.githubusercontent.com/63355/65459801-3f0d6500-de16-11e9-874f-e95ad8871890.png)
> 
> or
> 
> ![image](https://user-images.githubusercontent.com/63355/65459875-68c68c00-de16-11e9-81a6-17273629247e.png)
> 
> response
> 
> ![image](https://user-images.githubusercontent.com/63355/65459942-83990080-de16-11e9-8a9b-a1c2a2f0e3ac.png)
> 
> Happy to answer any questions anyone might have.

Thanks for reporting the issue! We haven't supported this feature yet. Will try to make it happen and update here if any progress.

**Comment by drusellers** [comment]
Thank you, if there is anything I can do to help, please don't hesitate to ping me.

**Comment by dai-chen** [comment]
@drusellers We've been working on this and able to connect to Tableau via our JDBC driver: https://github.com/opendistro-for-elasticsearch/sql-jdbc/blob/master/docs/tableau.md. While we're still fixing bugs, you can track our progress by issue label "BI Integration".

**Comment by abbashus** [comment]
JDBC driver has been released. The latest version can be downloaded from here.
https://opendistro.github.io/for-elasticsearch/downloads.html

To use JDBC with Tableau, see [documentation](https://github.com/opendistro-for-elasticsearch/sql-jdbc/blob/master/docs/tableau.md).
