### ISSUE TITLE
escaping forward slashes

### ISSUE THREAD

**Issue by JacobJohansen** [opendistro-for-elasticsearch/sql#32]
I'm having issues running a like query with forward slashes. it doesn't fail but it also doesn't return anything

```
GET _opendistro/_sql
{
  "query": "SELECT ClientASN, ClientRequestURI FROM cloudflare WHERE ClientRequestURI like '/my/uri'"
}
```

**Comment by dai-chen** [comment]
Thanks for report this! Just did a quick check. From the _explain output, we're using ES [wildcard query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-wildcard-query.html) for `LIKE`. I assume your `ClientRequestURI` is of text type and was analyzed into tokens by standard analyzer during indexing like this:

```
POST _analyze
{
  "analyzer": "standard",
  "text": "/my/uri"
}

{
  "tokens" : [
    {
      "token" : "my",
      "start_offset" : 1,
      "end_offset" : 3,
      "type" : "<ALPHANUM>",
      "position" : 0
    },
    {
      "token" : "uri",
      "start_offset" : 4,
      "end_offset" : 7,
      "type" : "<ALPHANUM>",
      "position" : 1
    }
  ]
}
```

If so, you can either use pattern to match token ('my', 'uri') or predefine the field as `keyword` instead of `text`. Please provide more information about your data if this is not the case. Thanks!

**Comment by JacobJohansen** [comment]
thanks
