### ISSUE TITLE
date_histogram is not working with ElasticSearch 7.4.2

### ISSUE THREAD

**Issue by konstantin-kornienko** [opendistro-for-elasticsearch/sql#327]
opendistro sql release: 1.4.0
elasticsearch: 7.4.2

I'm trying to post the following request:

```
GET /_opendistro/_sql?format=jdbc
{
  "query": "SELECT *  from access GROUP BY date_histogram(field='@timestamp','interval'='1m')",
   "filter" : {
    "range" : {
       "@timestamp": {
          "gte": "now-5m"
        }
    }
  }
}
```

recieving an error:
```
#! Deprecation: [interval] on [date_histogram] is deprecated, use [fixed_interval] or [calendar_interval] in the future.
{
  "error": {
    "reason": "There was internal problem at backend",
    "details": "The following method is not supported in Schema: date_histogram",
    "type": "UnsupportedOperationException"
  },
  "status": 500
}
```

**Comment by konstantin-kornienko** [comment]
btw, is it possible to specify this condition in WHERE somehow? Thanks!

```
 "range" : {
       "@timestamp": {
          "gte": "now-5m"
        }
    }
```

**Comment by dai-chen** [comment]
Thanks for reporting! Will look into the issue.

**Comment by chloe-zh** [comment]
Hi @konstantin-kornienko , we have reproduced the error you reported and it turns out to be the issue of the jdbc formatter since the JDBC driver does not support date_histogram aggregations. However, others formats (eg. csv) do support date_histogram aggregations.

Sorry we don't support plus/minus operations in datetime type yet. We will support it in the future.

**Comment by konstantin-kornienko** [comment]
Can cofirm that CSV is working fine :) Thank you!
