### ISSUE TITLE
can not build on mac

### ISSUE THREAD

**Issue by luweijie007** [opendistro-for-elasticsearch/sql#338]
![image](https://user-images.githubusercontent.com/7186190/72045238-97e30980-32f0-11ea-85ad-684ce2f0579b.png)

first error path has blank? second error If I need run some RMIServer?

**Comment by dai-chen** [comment]
Hi @luweijie007 , I think that was caused by integTestCluster process hung there which was created by previous run and didn't exit normally.

You can check out its process ID (`ps aux | grep -i elasticsearch` or integTestRunner) and kill it. Please have a look at our Development Guide: https://github.com/opendistro-for-elasticsearch/sql/blob/master/docs/developing.rst#gradle-build

**Comment by dai-chen** [comment]
Closing as no update from the requester.
