### ISSUE TITLE
JDBC Integration Test

### ISSUE THREAD

**Issue by penghuo** [opendistro-for-elasticsearch/sql#617]
Add the integration test for JDBC driver

**Comment by dai-chen** [comment]
We've used JDBC driver in comparison test to run test queries against our plugin via JDBC driver: https://github.com/opendistro-for-elasticsearch/sql/blob/893cd18fe5ce1fc7d3016c76567ce6e5ca834182/integ-test/src/test/java/com/amazon/opendistroforelasticsearch/sql/sql/SQLCorrectnessIT.java#L31.

However we need to figure out how to depend on latest code instead of JDBC driver released to Maven repo.

**Comment by dai-chen** [comment]
We've added a task to compile JDBC driver whenever comparison test run: https://github.com/opendistro-for-elasticsearch/sql/blob/develop/integ-test/build.gradle#L192
