### ISSUE TITLE
cursor not returning  _opendistro/_sql/

### ISSUE THREAD

**Issue by chezhiane** [opendistro-for-elasticsearch/sql#621]
when fetch size provided - still not returning cursor.

# The JSON body to accompany the request (if necessary)
payload = {
  "fetch_size" : 3,
  "query" : "SELECT * from movies"
}

**Comment by dai-chen** [comment]
@chezhiane Thanks for reporting the issue! I guess it's because our pagination feature is still disabled by default at the moment. Could you try to change the plugin setting to enable it? https://github.com/opendistro-for-elasticsearch/sql/blob/master/docs/user/admin/settings.rst#opendistro-sql-cursor-enabled
