### ISSUE TITLE
support "SELECT 1"

### ISSUE THREAD

**Issue by dictcp** [opendistro-for-elasticsearch/sql#64]
Why
----
there are BI tool (eg. metabase) using simple dummy query "SELECT 1" to detect if the connection works.
But it is not supported according to
https://opendistro.github.io/for-elasticsearch-docs/docs/sql/operations/

How
----
Can consider to hardcode a response "1"

**Comment by penghuo** [comment]
Thanks for bringing this up. We are looking into this now.

**Comment by jordanw-bq** [comment]
We are currently encountering this issue when connecting the ODBC driver to Tableau. Looking at the linked PR (#68), the issue was not fully addressed.

The particular case that needs to be supported is for the exact query `SELECT 1`, without a FROM clause. The expected result set should be a single column (column name does not matter, can use the default approach for situations like unaliased functions in the SELECT list), and a single row containing the integer `1`.

Example from Presto:
```
 _col0
-------
     1
```

This seems to be necessary for using the ODBC driver with Tableau, as we have so far not found a way to disable this type of discovery query.

**Comment by dai-chen** [comment]
We have the issue for tracking: https://github.com/opendistro-for-elasticsearch/sql/issues/264
