### ISSUE TITLE
Timeout when running delete

### ISSUE THREAD

**Issue by mporracindie** [opendistro-for-elasticsearch/sql#72]
Hi,

Im getting timeout when running big delete querys. Is it possible to ask for it to run on background? or something like that?

Thanks!

**Comment by arsen-es** [comment]
Thanks for reporting this.

Doesn't any of the suggestions in issue #54 help?

**Comment by mporracindie** [comment]
@arsen-es No, in this case im ussing Postman and i setted up no timeout on the client. 
But ones again im doing querys like:

`DELETE FROM index WHERE date_format(element.date_created,'Y-MM-dd') <= '2019-05-13'"`

And i know this are big deletes since a simple count returns over 10M docs.

**Comment by mporracindie** [comment]
Im getting things like:

```
{
    "took": 331903,
    "timed_out": false,
    "total": 10251256,
    "updated": 0,
    "created": 0,
    "deleted": 1327999,
    "batches": 1328,
    "version_conflicts": 1,
    "noops": 0,
    "retries": {
        "bulk": 0,
        "search": 0
    },
    "throttled_millis": 0,
    "requests_per_second": -1,
    "throttled_until_millis": 0,
    "failures": [
        {
            "index": "index",
            "type": "metrics",
            "id": "27947136862",
            "cause": {
                "type": "version_conflict_engine_exception",
                "reason": "[metrics][27947136862]: version conflict, required seqNo [49378113], primary term [1]. current document has seqNo [220660042] and primary term [3]",
                "index_uuid": "ZTdbstcxRVGabSuxH7js6w",
                "shard": "0",
                "index": "index"
            },
            "status": 409
        }
    ]
}
```

**Comment by arsen-es** [comment]
In postman there should be a way to update the client-side timeout setting. Check out the `XHR Timeout` or `Request timeout`  (depending on the version of postman) under `Settings` -> `General`.

However, the response you pasted does not indicate a timeout, but rather a conflict between versions of documents. Basically you're trying to access/delete a document wich has been modified since you made the request. Did you make other requests while the `DELETE` one was running?

**Comment by mporracindie** [comment]
@arsen-es You were right. i ll see how i can work arround this.
