### ISSUE TITLE
Permissions bypassed by specifying format=

### ISSUE THREAD

**Issue by gsmith-sas** [opendistro-for-elasticsearch/sql#806]
When I submit the following query (via the Dev Console):
```
POST _opendistro/_sql
{"query": """
  select @timestamp, level, message  from viya_logs-buzz-2020-10-29
"""}
```
It fails with a 403 return code and a message indicating that I do not have the right permissions (as shown below)
```
{
  "error": {
    "reason": "Error occurred in Elasticsearch engine: no permissions for [indices:admin/mappings/fields/get] and User [name=buzz, backend_roles=[buzz_kibana_users], requestedTenant=null]",
    "details": """org.elasticsearch.ElasticsearchSecurityException: no permissions for [indices:admin/mappings/fields/get] and User [name=buzz, backend_roles=[buzz_kibana_users], requestedTenant=null]
For more details, please send request for Json format to see the raw response from elasticsearch engine.""",
    "type": "ElasticsearchSecurityException"
  },
  "status": 403
}
```
However, if I specify a format such as JSON or CSV (as shown below), the query executes successfully and returns data.
```
POST _opendistro/_sql?format=csv
{"query": """
  select @timestamp, level, message  from viya_logs-buzz-2020-10-29
"""}
```
I don't know which behavior is "correct" but I would not have expected including the format to impact which permission are needed.

I have granted this particular user the "search" action group permission to the index.  That is sufficient to allow them to view documents from this index in various Kibana visualizations and dashboards.  Therefore, I would have expected it to be sufficient for the same user to submit SQL queries against the index.

I have confirmed the same behavior in ODFE 1.7.0 and ODFE 1.11.0.

**Comment by gsmith-sas** [comment]
A few more details:
If I specify:
- format=csv, the query succeeds and returns data.
- format=json (as suggested in the error message), the query succeeds and returns data
- format=jdbc, the query fails in the same way as if I do not specify any format

**Comment by dai-chen** [comment]
@gsmith-sas Thanks for reporting the issue! This looks strange because all different formatters actually share the same code until response formatting. I'm thinking any easy way to reproduce this issue from my side.

**Comment by dai-chen** [comment]
@gsmith-sas We've tested this issue from our side. Actually your user already has indices:data/read/search* permission on the index, so you're supposed to have the access by either our SQL plugin or ES _search endpoint. Your first query without format parameter (default JDBC formatter) throws permission exception. The reason is that our JDBC formatter calls ES get mapping API to generate response. This is the difference between JDBC and other formatter which caused the error.

As our doc and the error above suggests, you need to add indices:admin/mappings/fields/get to your user role. Let me know if any other question. Thanks!

**Comment by dai-chen** [comment]
Closing. Feel free to reopen if anything else. Thanks!
